//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfJDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class JdtTask
    {
        public int TaskId { get; set; }
        public Nullable<int> MinSets { get; set; }
        public Nullable<int> MaxSets { get; set; }
        public Nullable<int> MinReps { get; set; }
        public Nullable<int> MaxReps { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
