//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfJDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Plans = new HashSet<Plan>();
            this.PreConsumers = new HashSet<PreConsumer>();
            this.UserProfiles1 = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PictureUrl { get; set; }
        public Nullable<int> ContentAuthorId { get; set; }
    
        public virtual ICollection<Plan> Plans { get; set; }
        public virtual ICollection<PreConsumer> PreConsumers { get; set; }
        public virtual ICollection<UserProfile> UserProfiles1 { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
